theme[main_bg]=""

theme[main_fg]="#{{colors.on_surface.default.hex}}"
theme[title]="#{{colors.primary.default.hex}}"

theme[hi_fg]="#{{colors.tertiary.default.hex}}"

theme[selected_bg]="#{{colors.primary_container.default.hex}}"
theme[selected_fg]="#{{colors.on_primary_container.default.hex}}"

theme[inactive_fg]="#{{colors.outline.default.hex}}"

theme[graph_text]="#{{colors.on_surface_variant.default.hex}}"

theme[meter_bg]="#{{colors.surface_variant.default.hex}}"

theme[proc_misc]="#{{colors.secondary.default.hex}}"

theme[div_line]="#{{colors.surface_variant.default.hex}}"

theme[cpu_box]="#{{colors.primary.default.hex}}"
theme[mem_box]="#{{colors.secondary.default.hex}}"
theme[net_box]="#{{colors.tertiary.default.hex}}"
theme[proc_box]="#{{colors.primary.default.hex}}"

theme[temp_start]="#{{colors.primary.default.hex}}"
theme[temp_mid]="#{{colors.inverse_primary.default.hex}}"
theme[temp_end]="#{{colors.error.default.hex}}"

theme[cpu_start]="#{{colors.primary.default.hex}}"
theme[cpu_mid]="#{{colors.secondary.default.hex}}"
theme[cpu_idlescent]="#{{colors.tertiary.default.hex}}"

