theme[main_bg]=""

theme[main_fg]="#{{colors.on_surface.hex}}"
theme[title]="#{{colors.primary.hex}}"

theme[hi_fg]="#{{colors.tertiary.hex}}"

theme[selected_bg]="#{{colors.primary_container.hex}}"
theme[selected_fg]="#{{colors.on_primary_container.hex}}"

theme[inactive_fg]="#{{colors.outline.hex}}"

theme[graph_text]="#{{colors.on_surface_variant.hex}}"

theme[meter_bg]="#{{colors.surface_container_highest.hex}}"

theme[proc_misc]="#{{colors.secondary.hex}}"

theme[div_line]="#{{colors.surface_variant.hex}}"

theme[cpu_box]="#{{colors.primary.hex}}"
theme[mem_box]="#{{colors.secondary.hex}}"
theme[net_box]="#{{colors.tertiary.hex}}"
theme[proc_box]="#{{colors.primary.hex}}"

theme[temp_start]="#{{colors.primary.hex}}"
theme[temp_mid]="#{{colors.inverse_primary.hex}}"
theme[temp_end]="#{{colors.error.hex}}"

theme[cpu_start]="#{{colors.primary.hex}}"
theme[cpu_mid]="#{{colors.secondary.hex}}"
theme[cpu_idlescent]="#{{colors.tertiary.hex}}"
